services:
    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin
        depends_on:
            - mysql
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=mysql
            - PMA_USER=root
            - PMA_PASSWORD=mysql
        ports:
            - "3001:80"
volumes:
    mysql_data:
